from __future__ import annotations

CANONICAL_EVENTS: dict[str, str] = {
    "conversation.started": "lawim.conversation.started",
    "message.received": "lawim.message.received",
    "intent.identified": "lawim.intent.identified",
    "intent.ambiguous": "lawim.intent.ambiguous",
    "fact.confirmed": "lawim.fact.confirmed",
    "fact.ambiguous": "lawim.fact.ambiguous",
    "fact.superseded": "lawim.fact.superseded",
    "project.selected": "lawim.project.selected",
    "project.created": "lawim.project.created",
    "project.closed": "lawim.project.closed",
    "search.requested": "lawim.search.requested",
    "search.results_available": "lawim.search.results_available",
    "search.zero_results": "lawim.search.zero_results",
    "match.proposed": "lawim.match.proposed",
    "match.selected": "lawim.match.selected",
    "consent.requested": "lawim.consent.requested",
    "consent.granted": "lawim.consent.granted",
    "consent.denied": "lawim.consent.denied",
    "relationship.created": "lawim.relationship.created",
    "relationship.rejected": "lawim.relationship.rejected",
    "visit.requested": "lawim.visit.requested",
    "visit.confirmed": "lawim.visit.confirmed",
    "visit.completed": "lawim.visit.completed",
    "handover.requested": "lawim.handover.requested",
    "handover.resolved": "lawim.handover.resolved",
    "clarification.repeated": "lawim.clarification.repeated",
    "clarification.loop_exceeded": "lawim.clarification.loop_exceeded",
    "state.transition": "lawim.state.transition",
    "state.error": "lawim.state.error",
    "state.recovered": "lawim.state.recovered",
}
