import { Badge, Card, PageShell, Button } from '@ui';
import { BrainOrchestrator, BrainRegistry, createDemoBrainContext, createDemoIntent } from '@brain';
import { ConversationEngine } from '@conversation';
import { MemoryService, SummaryGenerator, createMemoryRetentionPolicy } from '@memory';
import { DigitalTwin, DigitalTwinDashboard } from '@digital-twin';
import { ObservationCollector, LearningAnalyzer, RecommendationGenerator, ValidationWorkflow } from '@learning';

export function BrainConsolePage() {
  const registry = new BrainRegistry();
  registry.register({
    name: 'search',
    description: 'Search and route property demand',
    capabilities: ['search'],
    supportedIntents: ['SearchProperty'],
    priority: 1,
    health: 'healthy',
    availability: 'available',
    async execute() {
      return { outcome: 'search-ready' };
    }
  });

  const orchestrator = new BrainOrchestrator(registry);
  const conversationEngine = new ConversationEngine();
  const memory = new MemoryService({ retentionPolicy: createMemoryRetentionPolicy({ maxItems: 3, retainRaw: false }) });
  const summaryGenerator = new SummaryGenerator();
  const collector = new ObservationCollector();
  const analyzer = new LearningAnalyzer();
  const recommendationGenerator = new RecommendationGenerator();
  const validationWorkflow = new ValidationWorkflow();
  const digitalTwin = new DigitalTwin({
    id: 'project-1',
    name: 'Digital Twin Demo',
    description: 'A demo project for the new orchestrator layer',
    state: 'active',
    progress: 74,
    milestones: [],
    metrics: { engagement: 82, readiness: 76, confidence: 80 },
    timeline: [],
    createdAt: new Date().toISOString()
  });

  const conversationResult = conversationEngine.analyze({
    id: 'conv-1',
    sessionId: 'session-1',
    mode: 'business',
    messages: [{ id: 'm-1', role: 'user', content: 'I need to search a luxury villa in Lyon', timestamp: new Date().toISOString() }],
    metadata: { source: 'web' },
    createdAt: new Date().toISOString()
  });
  memory.addConversation({
    id: 'conv-1',
    sessionId: 'session-1',
    mode: 'business',
    messages: [{ id: 'm-1', role: 'user', content: 'I need to search a luxury villa in Lyon', timestamp: new Date().toISOString() }],
    metadata: { source: 'web' },
    createdAt: new Date().toISOString()
  });
  const summary = summaryGenerator.generate(memory.getConversationHistory()[0]);
  const observations = collector.collect([{ id: 'e-1', source: 'analytics', type: 'trend', payload: { metric: 'conversion', value: 0.82 }, createdAt: new Date().toISOString() }]);
  const recommendations = analyzer.analyze(observations);
  const recommendation = recommendationGenerator.generate(recommendations[0]);
  const validatedRecommendation = validationWorkflow.validate(recommendation, 'accepted');
  const dashboard = new DigitalTwinDashboard([digitalTwin]).build();

  return (
    <PageShell eyebrow="LAWIM Brain" title="Brain Console" description="A new orchestration console for intent routing, conversations, memory, digital twin, and learning." actions={<Button>Launch review</Button>}>
      <div className="grid gap-6 xl:grid-cols-[1.2fr_0.8fr]">
        <Card title="Brain execution" description="Execution plan generated by the new orchestration layer.">
          <div className="mt-4 flex flex-wrap gap-2">
            <Badge variant="info">Intent: SearchProperty</Badge>
            <Badge variant="success">Plan ready</Badge>
          </div>
          <div className="mt-4 rounded-2xl border border-slate-800 bg-slate-950/60 p-4 text-sm text-slate-300">
            {JSON.stringify(orchestrator.orchestrate(createDemoIntent('SearchProperty', 'Find a luxury villa in Lyon'), createDemoBrainContext()).then(() => 'ready'))}
          </div>
        </Card>
        <Card title="Conversation" description="Current conversation intent and summary.">
          <div className="mt-4 space-y-2 text-sm text-slate-300">
            <p><strong>Intent:</strong> {conversationResult.intent.type}</p>
            <p><strong>Summary:</strong> {conversationResult.summary}</p>
          </div>
        </Card>
      </div>
      <div className="mt-6 grid gap-6 md:grid-cols-2 xl:grid-cols-4">
        <Card title="Memory" description="The memory layer keeps retained facts and summaries.">
          <p className="mt-4 text-sm text-slate-300">{summary.summary}</p>
        </Card>
        <Card title="Digital Twin" description="Aggregated project state from the twin layer.">
          <p className="mt-4 text-sm text-slate-300">{dashboard.projects[0].name} • {dashboard.projects[0].progress}%</p>
        </Card>
        <Card title="Learning" description="Observed trends and recommendations.">
          <p className="mt-4 text-sm text-slate-300">{validatedRecommendation.title} • {validatedRecommendation.status}</p>
        </Card>
        <Card title="Module Registry" description="Available orchestration modules.">
          <p className="mt-4 text-sm text-slate-300">{registry.list().length} modules registered</p>
        </Card>
      </div>
    </PageShell>
  );
}
