from __future__ import annotations

PROJECT_PROFILE_CREATED = "PROJECT_PROFILE_CREATED"
FIELD_CANDIDATE_RECEIVED = "FIELD_CANDIDATE_RECEIVED"
FIELD_NORMALIZED = "FIELD_NORMALIZED"
FIELD_VALIDATED = "FIELD_VALIDATED"
FIELD_REJECTED = "FIELD_REJECTED"
PROFILE_PATCH_CREATED = "PROFILE_PATCH_CREATED"
PROFILE_PATCH_APPLIED = "PROFILE_PATCH_APPLIED"
PROFILE_PATCH_REJECTED = "PROFILE_PATCH_REJECTED"
PROFILE_UPDATED = "PROFILE_UPDATED"
FIELD_CONFLICT_DETECTED = "FIELD_CONFLICT_DETECTED"
FIELD_CONFLICT_RESOLVED = "FIELD_CONFLICT_RESOLVED"
PROFILE_COMPLETENESS_CHANGED = "PROFILE_COMPLETENESS_CHANGED"
PROFILE_SNAPSHOT_CREATED = "PROFILE_SNAPSHOT_CREATED"
PROFILE_SNAPSHOT_RESTORED = "PROFILE_SNAPSHOT_RESTORED"
PROFILE_MIGRATED_FROM_V2 = "PROFILE_MIGRATED_FROM_V2"

ALL_EVENTS: tuple[str, ...] = (
    PROJECT_PROFILE_CREATED,
    FIELD_CANDIDATE_RECEIVED,
    FIELD_NORMALIZED,
    FIELD_VALIDATED,
    FIELD_REJECTED,
    PROFILE_PATCH_CREATED,
    PROFILE_PATCH_APPLIED,
    PROFILE_PATCH_REJECTED,
    PROFILE_UPDATED,
    FIELD_CONFLICT_DETECTED,
    FIELD_CONFLICT_RESOLVED,
    PROFILE_COMPLETENESS_CHANGED,
    PROFILE_SNAPSHOT_CREATED,
    PROFILE_SNAPSHOT_RESTORED,
    PROFILE_MIGRATED_FROM_V2,
)
