from __future__ import annotations

QUALIFICATION_REQUESTED = "QUALIFICATION_REQUESTED"
QUALIFICATION_STARTED = "QUALIFICATION_STARTED"
QUALIFICATION_COMPLETED = "QUALIFICATION_COMPLETED"
QUALIFICATION_SCORE_CHANGED = "QUALIFICATION_SCORE_CHANGED"
QUALIFICATION_LEVEL_CHANGED = "QUALIFICATION_LEVEL_CHANGED"
QUALIFICATION_BLOCKER_DETECTED = "QUALIFICATION_BLOCKER_DETECTED"
DECISION_REQUESTED = "DECISION_REQUESTED"
DECISION_COMPLETED = "DECISION_COMPLETED"
NEXT_ACTION_SELECTED = "NEXT_ACTION_SELECTED"
HUMAN_HANDOVER_REQUIRED = "HUMAN_HANDOVER_REQUIRED"
PROJECT_BRAIN_UPDATED = "PROJECT_BRAIN_UPDATED"

ALL_EVENTS: tuple[str, ...] = (
    QUALIFICATION_REQUESTED,
    QUALIFICATION_STARTED,
    QUALIFICATION_COMPLETED,
    QUALIFICATION_SCORE_CHANGED,
    QUALIFICATION_LEVEL_CHANGED,
    QUALIFICATION_BLOCKER_DETECTED,
    DECISION_REQUESTED,
    DECISION_COMPLETED,
    NEXT_ACTION_SELECTED,
    HUMAN_HANDOVER_REQUIRED,
    PROJECT_BRAIN_UPDATED,
)
