"""LAWIM_V2 executable baseline package."""

from __future__ import annotations

from dataclasses import dataclass

from .conversation_registry import (
    ConversationArchiveManager,
    ConversationArchiveManifest,
    ConversationLifecycleEngine,
    ConversationRegistry,
    ConversationRestoreEngine,
    ConversationStorageProvider,
    OVHStorageOptimizer,
    StorageOrchestrator,
)
from .storage_registry import (
    GoogleDriveConfigurationModel,
    GoogleDriveConnector,
    StorageResource,
    StorageResourceRegistry,
    StorageRoutingPolicy,
    StorageSetupWizard as _StorageSetupWizard,
    StorageUsageThresholds,
)
from .google_drive_connector import (
    GoogleDriveOAuthCredentials,
    build_default_google_drive_connectors,
)
from .credential_vault import (
    AuditTrail,
    CredentialAuditLogger,
    CredentialEncryptor,
    CredentialMasker,
    CredentialProvider,
    CredentialRecord,
    CredentialReference,
    CredentialRotationManager,
    CredentialRotationPolicy,
    CredentialScanner,
    CredentialScope,
    CredentialStatus,
    CredentialType,
    CredentialValidator,
    CredentialVault,
    GitSecretGuard,
    LogMasker,
    SecretScanner,
    build_default_credential_records,
    build_default_credential_vault,
)
from .security import (
    AADAuthResult,
    AADAuthenticator,
    AADAuthenticationProvider,
    AADConfig,
    AADAuditLogger,
    AADIdentityProvider,
    AADSession,
    AADSessionManager,
    AuthenticationResult,
    AuthorizationDecision,
    BaseAuthorizer,
    ClaimsBasedAuthorizer,
    ClaimsManager,
    ExternalSecretProvider,
    GroupMapper,
    Identity,
    IdentityGroup,
    IdentityProvider,
    IdentityValidator,
    IdentityProviderKind,
    LocalIdentityProvider,
    MockAccessToken,
    MockIDToken,
    MockRefreshToken,
    PolicyBasedAuthorizer,
    RoleBasedAuthorizer,
    RoleMapper,
    SecretProvider,
    resolve_aad_config,
)

@dataclass(slots=True)
class StorageSetupWizard(_StorageSetupWizard):
    # Preserve the legacy activation plan shape expected by downstream compatibility tests.
    steps: tuple[str, ...] = (
        "Register the credential vault",
        "Declare the 10 Google Drive resources",
        "Bind credential references",
        "Map the official routing policy",
        "Validate OAuth connection",
        "Validate permissions",
        "Create the automatic folders",
        "Run the read/write validation",
        "Run the upload/download validation",
        "Review blocked-drive alerts",
        "Run the final validation",
    )

__all__ = [
    "__version__",
    "AADAuthResult",
    "AADAuthenticator",
    "AADConfig",
    "AADAuditLogger",
    "AADIdentityProvider",
    "AADSession",
    "AADSessionManager",
    "AuthorizationDecision",
    "BaseAuthorizer",
    "ClaimsBasedAuthorizer",
    "ClaimsManager",
    "ExternalSecretProvider",
    "GroupMapper",
    "Identity",
    "IdentityGroup",
    "IdentityProvider",
    "IdentityProviderKind",
    "LocalIdentityProvider",
    "MockAccessToken",
    "MockIDToken",
    "MockRefreshToken",
    "PolicyBasedAuthorizer",
    "RoleBasedAuthorizer",
    "RoleMapper",
    "SecretProvider",
    "ConversationArchiveManager",
    "ConversationArchiveManifest",
    "ConversationLifecycleEngine",
    "ConversationRegistry",
    "ConversationRestoreEngine",
    "ConversationStorageProvider",
    "AuditTrail",
    "CredentialAuditLogger",
    "CredentialEncryptor",
    "CredentialMasker",
    "CredentialProvider",
    "CredentialRecord",
    "CredentialReference",
    "CredentialRotationManager",
    "CredentialRotationPolicy",
    "CredentialScanner",
    "CredentialScope",
    "CredentialStatus",
    "CredentialType",
    "CredentialValidator",
    "CredentialVault",
    "GitSecretGuard",
    "LogMasker",
    "GoogleDriveConfigurationModel",
    "GoogleDriveConnector",
    "GoogleDriveOAuthCredentials",
    "build_default_google_drive_connectors",
    "build_default_credential_records",
    "build_default_credential_vault",
    "OVHStorageOptimizer",
    "SecretScanner",
    "StorageResource",
    "StorageResourceRegistry",
    "StorageRoutingPolicy",
    "StorageSetupWizard",
    "StorageUsageThresholds",
    "StorageOrchestrator",
    "resolve_aad_config",
]

__version__ = "0.1.0"
