BUSINESS_PROFILES = {
    'buyer': {'label': 'Acheteur', 'icon': '🏠', 'description': 'Recherche un bien à acheter'},
    'tenant': {'label': 'Locataire', 'icon': '🔑', 'description': 'Recherche un bien à louer'},
    'land_seeker': {'label': 'Chercheur de terrain', 'icon': '🌍', 'description': 'Recherche un terrain'},
    'builder': {'label': 'Porteur de projet', 'icon': '🏗️', 'description': 'Projet de construction'},
    'investor': {'label': 'Investisseur', 'icon': '💰', 'description': 'Investissement immobilier'},
    'owner': {'label': 'Propriétaire', 'icon': '🏘️', 'description': 'Gère ses biens'},
    'property_manager': {'label': 'Gestionnaire', 'icon': '🏢', 'description': 'Gère des biens pour le compte d\'autrui'},
    'real_estate_agent': {'label': 'Agent immobilier', 'icon': '🏠', 'description': 'Agent ou agence immobilière'},
    'notary': {'label': 'Notaire', 'icon': '⚖️', 'description': 'Service notarial'},
    'surveyor': {'label': 'Géomètre', 'icon': '📐', 'description': 'Service de géomètre'},
    'architect': {'label': 'Architecte', 'icon': '🏛️', 'description': 'Service d\'architecture'},
    'engineer': {'label': 'Ingénieur', 'icon': '👷', 'description': 'Ingénierie et conseil technique'},
    'technician': {'label': 'Technicien', 'icon': '🔧', 'description': 'Service technique spécialisé'},
    'contractor': {'label': 'Entrepreneur', 'icon': '🧱', 'description': 'Entreprise de construction'},
    'bank': {'label': 'Banque', 'icon': '💳', 'description': 'Service bancaire et financier'},
    'financing': {'label': 'Organisme de financement', 'icon': '💰', 'description': 'Financement et crédit'},
    'photographer': {'label': 'Photographe', 'icon': '📸', 'description': 'Photographie immobilière'},
    'decorator': {'label': 'Décorateur', 'icon': '🪑', 'description': 'Décoration intérieure'},
    'electrician': {'label': 'Électricien', 'icon': '⚡', 'description': 'Installation électrique'},
    'plumber': {'label': 'Plombier', 'icon': '🚰', 'description': 'Plomberie et sanitaires'},
    'cleaner': {'label': 'Service de nettoyage', 'icon': '🧹', 'description': 'Nettoyage professionnel'},
    'mover': {'label': 'Déménageur', 'icon': '🚚', 'description': 'Service de déménagement'},
    'insurer': {'label': 'Assureur', 'icon': '🛡️', 'description': 'Assurance immobilière'},
    'lawyer': {'label': 'Juriste', 'icon': '⚖️', 'description': 'Conseil juridique'},
    'agent': {'label': 'Agent LAWIM', 'icon': '🤝', 'description': 'Agent d\'accompagnement LAWIM'},
}
