from __future__ import annotations

from typing import Any, Protocol, runtime_checkable


@runtime_checkable
class RepositoryTransaction(Protocol):
    def record_event(self, kind: str, payload: dict[str, object]) -> None: ...


@runtime_checkable
class PersistenceBackend(Protocol):
    def backend_profile(self) -> dict[str, object]: ...
    def schema_version(self) -> int: ...
    def close(self) -> None: ...


@runtime_checkable
class PropertyRepository(Protocol):
    def create_property(self, **fields: Any) -> dict[str, object]: ...
    def update_property(self, property_id: int, **fields: Any) -> dict[str, object]: ...
    def delete_property(self, property_id: int, *, hard: bool = False) -> dict[str, object]: ...
    def get_property(self, property_id: int, *, include_deleted: bool = False) -> dict[str, object]: ...
    def list_properties(self, **filters: Any) -> dict[str, object]: ...
    def publish_property(self, property_id: int, *, version: int | None = None) -> dict[str, object]: ...


@runtime_checkable
class MediaRepository(Protocol):
    def create_media(self, **fields: Any) -> dict[str, object]: ...
    def update_media(self, media_id: int, **fields: Any) -> dict[str, object]: ...
    def delete_media(self, media_id: int, *, hard: bool = False) -> dict[str, object]: ...
    def get_media(self, media_id: int, *, include_deleted: bool = False) -> dict[str, object]: ...
    def list_media(self, **filters: Any) -> dict[str, object]: ...


@runtime_checkable
class GeoRepository(Protocol):
    def search_locations(self, *, query: str | None = None, limit: int = 20) -> list[dict[str, object]]: ...
    def normalize_location(
        self,
        *,
        city: str,
        country: str,
        region: str | None = None,
        address_line: str | None = None,
        postal_code: str | None = None,
    ) -> dict[str, object]: ...


@runtime_checkable
class LawimRepositoryContract(
    PersistenceBackend,
    PropertyRepository,
    MediaRepository,
    GeoRepository,
    Protocol,
):
    def list_user_ids_by_organization(self, organization_id: int) -> list[int]: ...
    def summary(self) -> dict[str, object]: ...
    def bootstrap_payload(self, *, token: str | None = None) -> dict[str, object]: ...
