from __future__ import annotations

from typing import Any, Protocol, runtime_checkable


@runtime_checkable
class DemoUserPort(Protocol):
    def create_or_update(self, ref_id: str, email: str, full_name: str, role: str, password: str | None = None, can_login: bool = True, account_status: str = "active", org_id: str | None = None) -> str: ...
    def find_by_ref(self, ref_id: str) -> dict[str, Any] | None: ...


@runtime_checkable
class DemoAuthPort(Protocol):
    def verify(self, email: str, password: str) -> tuple[bool, str, str]: ...
    def update_password(self, email: str, new_password: str) -> None: ...


@runtime_checkable
class DemoPropertyPort(Protocol):
    def create(self, owner_id: str, created_by: str, property_type: str, transaction_type: str, city: str, district: str, price: float, agent_id: str = "", org_id: str = "", title: str = "") -> dict[str, Any]: ...
    def transition(self, property_id: str, new_status: str, changed_by: str) -> str: ...
    def find_by_id(self, property_id: str) -> dict[str, Any] | None: ...
